//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class File_Info
    {
        public int Id { get; set; }
        public string F_Name { get; set; }
        public string Path { get; set; }
        public System.DateTime UploadedAt { get; set; }
        public int User_Id { get; set; }
        public int Tag_Id { get; set; }
    
        public virtual Tag Tag { get; set; }
        public virtual User User { get; set; }
    }
}
